services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444" # Altere para a porta que sua aplicação usa
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:your_password@db:5432/your_database_name
    volumes:
      - ${PWD}:/app

volumes:
  postgres_data: